export const exampleData = [
  {
    "Name": "TV Endgon",
    "Box": 22,
    "Box-Online": 22,
    "Box-Offline (1+ hour)": 0,
    "Box-Offline (1+ day)": 0,
    "Displays": 22,
    "Displays-Online": 22,
    "Displays-Offline (1+ hour)": 0,
    "Displays-Offline (1+ day)": 0,
  },
  {
    "Name": "KioskPowerBank",
    "Box": 1,
    "Box-Online": 1,
    "Box-Offline (1+ hour)": 0,
    "Box-Offline (1+ day)": 0,
    "Displays": 1,
    "Displays-Online": 1,
    "Displays-Offline (1+ hour)": 0,
    "Displays-Offline (1+ day)": 0,
  },
  {
    "Name": "Pillar",
    "Box": 0,
    "Box-Online": 0,
    "Box-Offline (1+ hour)": 0,
    "Box-Offline (1+ day)": 0,
    "Displays": 0,
    "Displays-Online": 0,
    "Displays-Offline (1+ hour)": 0,
    "Displays-Offline (1+ day)": 0,
  },
  {
    "Name": "Kiosk",
    "Box": 0,
    "Box-Online": 0,
    "Box-Offline (1+ hour)": 0,
    "Box-Offline (1+ day)": 0,
    "Displays": 0,
    "Displays-Online": 0,
    "Displays-Offline (1+ hour)": 0,
    "Displays-Offline (1+ day)": 0,
  },
  {
    "Name": "TV Walkway",
    "Box": 0,
    "Box-Online": 0,
    "Box-Offline (1+ hour)": 0,
    "Box-Offline (1+ day)": 0,
    "Displays": 0,
    "Displays-Online": 0,
    "Displays-Offline (1+ hour)": 0,
    "Displays-Offline (1+ day)": 0,
  },
  {
    "Name": "Video Wall",
    "Box": 0,
    "Box-Online": 0,
    "Box-Offline (1+ hour)": 0,
    "Box-Offline (1+ day)": 0,
    "Displays": 0,
    "Displays-Online": 0,
    "Displays-Offline (1+ hour)": 0,
    "Displays-Offline (1+ day)": 0,
  },
  {
    "Name": "Total",
    "Box": 23,
    "Box-Online": 23,
    "Box-Offline (1+ hour)": 0,
    "Box-Offline (1+ day)": 0,
    "Displays": 23,
    "Displays-Online": 23,
    "Displays-Offline (1+ hour)": 0,
    "Displays-Offline (1+ day)": 0,
  },
];
